# Generated by Django 4.0.1 on 2025-07-03 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='shorturl',
            name='created_at',
        ),
    ]
