# Generated by Django 4.0.1 on 2025-07-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_shorturl_clicks_remove_shorturl_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
