# Generated by Django 4.0.1 on 2025-07-05 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_shorturl_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='created_at',
        ),
    ]
